/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ro.utcluj.larkc.jsonservice.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the pluginMetrics service. Represents a row in the &quot;metricService_pluginMetrics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ro.utcluj.larkc.jsonservice.model.impl.pluginMetricsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ro.utcluj.larkc.jsonservice.model.impl.pluginMetricsImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a plugin metrics model instance should use the {@link pluginMetrics} interface instead.
 * </p>
 *
 * @author UTCluj
 * @see pluginMetrics
 * @see ro.utcluj.larkc.jsonservice.model.impl.pluginMetricsImpl
 * @see ro.utcluj.larkc.jsonservice.model.impl.pluginMetricsModelImpl
 * @generated
 */
public interface pluginMetricsModel extends BaseModel<pluginMetrics> {
	/**
	 * Gets the primary key of this plugin metrics.
	 *
	 * @return the primary key of this plugin metrics
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this plugin metrics
	 *
	 * @param pk the primary key of this plugin metrics
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the foo id of this plugin metrics.
	 *
	 * @return the foo id of this plugin metrics
	 */
	public long getFooId();

	/**
	 * Sets the foo id of this plugin metrics.
	 *
	 * @param fooId the foo id of this plugin metrics
	 */
	public void setFooId(long fooId);

	/**
	 * Gets the company id of this plugin metrics.
	 *
	 * @return the company id of this plugin metrics
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this plugin metrics.
	 *
	 * @param companyId the company id of this plugin metrics
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this plugin metrics.
	 *
	 * @return the user id of this plugin metrics
	 */
	public long getUserId();

	/**
	 * Sets the user id of this plugin metrics.
	 *
	 * @param userId the user id of this plugin metrics
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this plugin metrics.
	 *
	 * @return the user uuid of this plugin metrics
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this plugin metrics.
	 *
	 * @param userUuid the user uuid of this plugin metrics
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the user name of this plugin metrics.
	 *
	 * @return the user name of this plugin metrics
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this plugin metrics.
	 *
	 * @param userName the user name of this plugin metrics
	 */
	public void setUserName(String userName);

	/**
	 * Gets the create date of this plugin metrics.
	 *
	 * @return the create date of this plugin metrics
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this plugin metrics.
	 *
	 * @param createDate the create date of this plugin metrics
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this plugin metrics.
	 *
	 * @return the modified date of this plugin metrics
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this plugin metrics.
	 *
	 * @param modifiedDate the modified date of this plugin metrics
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the field1 of this plugin metrics.
	 *
	 * @return the field1 of this plugin metrics
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this plugin metrics.
	 *
	 * @param field1 the field1 of this plugin metrics
	 */
	public void setField1(String field1);

	/**
	 * Gets the field2 of this plugin metrics.
	 *
	 * @return the field2 of this plugin metrics
	 */
	public boolean getField2();

	/**
	 * Determines if this plugin metrics is field2.
	 *
	 * @return <code>true</code> if this plugin metrics is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this {$entity.humanName} is field2.
	 *
	 * @param field2 the field2 of this plugin metrics
	 */
	public void setField2(boolean field2);

	/**
	 * Gets the field3 of this plugin metrics.
	 *
	 * @return the field3 of this plugin metrics
	 */
	public int getField3();

	/**
	 * Sets the field3 of this plugin metrics.
	 *
	 * @param field3 the field3 of this plugin metrics
	 */
	public void setField3(int field3);

	/**
	 * Gets the field4 of this plugin metrics.
	 *
	 * @return the field4 of this plugin metrics
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this plugin metrics.
	 *
	 * @param field4 the field4 of this plugin metrics
	 */
	public void setField4(Date field4);

	/**
	 * Gets the field5 of this plugin metrics.
	 *
	 * @return the field5 of this plugin metrics
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this plugin metrics.
	 *
	 * @param field5 the field5 of this plugin metrics
	 */
	public void setField5(String field5);

	/**
	 * Gets a copy of this plugin metrics as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public pluginMetrics toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(pluginMetrics pluginMetrics);

	public int hashCode();

	public String toString();

	public String toXmlString();
}